### ISSUE TITLE
Build error: "entry module cannot be external"

### ISSUE THREAD

**Issue by lukePeavey** [ninetwenty-one/rotten-reviews#75]
**Describe the bug**

The `build` script fails with the following error: 

```sh
src/index.ts → dist/index.cjs.js, dist/index.esm.js...
[!] Error: Entry module cannot be external
Error: Entry module cannot be external
```

Environment: osx 10.14, node 12.5.0, npm 6.9.0

**To Reproduce**

1. `$ git clone https://github.com/ninetwenty-one/rotten-reviews.git`
2. `$ yarn`
3. `$ yarn run build`

**Screenshots**

![Error](https://i.imgur.com/4HsOqjY.png)

**Additional context**

Related: ezolenko/rollup-plugin-typescript2/issues/144

Updating rollup-plugin-typescript2 to `v0.21.2` fixed this (at least on my end)

**Comment by lukePeavey** [comment]
If this is something that should be fixed, I'd be happy to submit a PR.

**Comment by grikomsn** [comment]
Hello @lukePeavey, I haven’t got time to do some cleanup and fixes here. You can submit any kind of PR fixes and feature updates. 😄

**Comment by grikomsn** [comment]
Hello, @lukePeavey. I just re-bootstrapped the project using [tsdx](https://github.com/jaredpalmer/tsdx). Do try running `yarn build` or try the latest published package.

**Comment by lukePeavey** [comment]
Ok thanks! I'll try using the latest version
